# Generated by Django 2.0 on 2017-12-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jipiadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
