# Generated by Django 2.0 on 2017-12-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jipiadmin', '0002_evenement_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
