require('./../../templates/jipiS/index.html')
require('./../scss/index.scss')
LazyLoad = require('vanilla-lazyload')
hammertime = require('hammerjs')
Masonry = require('masonry-layout')
imagesLoaded = require('imagesloaded')
require('./index.js')
